---
#config docker on all masters and agents
- name: Enable OverlayFS
  lineinfile: dest=/etc/modules-load.d/overlay.conf state=present create=yes line="overlay" regexp="overlay"
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=60 timeout=180
- name: Configure systemd
  file: path=/etc/systemd/system/docker.service.d state=directory
- name: Configure systemd 2
  blockinfile:
      dest: /etc/systemd/system/docker.service.d/override.conf
      create: yes
      block: | 
        [Service]
        ExecStart=
        ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
- name: reload docker
  command: systemctl daemon-reload
- name: restart docker
  service: name=docker state=restarted enabled=yes
